name: Deckipedia
favicon: null
layout_spectrum: 0.31222658627666533
typography_spectrum: 0.4562896315474063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7567226300016046
  lightness: 0.55971944401972
  saturation: 0.7487217283342034
  rhythmicContrast: 0.48485341761261225
purpose: []
